version: '3'
services:
  core:
    build: ./core
    volumes:
    - "./core:/app"
    - "./config/:/config"
    environment:
    - MIX_ENV=dev
    - PORT=4000
    links:
    - rabbitmq
    - couchdb
    command: mix phx.server
    depends_on:
    - rabbitmq
    - couchdb
  nginx:
    image: nginx
    volumes:
    - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    - "./web/dist/:/var/www/dapnet"
    ports:
    - "80:80"
    - "5984:5984"
    depends_on:
    - rabbitmq
    - couchdb
    - core
    links:
    - rabbitmq
    - couchdb
    - core
  rabbitmq:
    image: rabbitmq
    ports:
    - "35197:35197"
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    volumes:
    - "./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
    - "./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"
  couchdb:
    image: couchdb
    volumes:
    - "./couchdb/:/opt/couchdb/data"
    environment:
    - COUCHDB_USER=admin
    - COUCHDB_PASSWORD=admin
